"""dismissed suggestions

Revision ID: 9ac0aea1070e
Revises: f7879d5046d3
Create Date: 2026-08-12 00:14:34.663366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ac0aea1070e'
down_revision: Union[str, None] = 'f7879d5046d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_suggestions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dismissed_suggestions_user_id'), 'dismissed_suggestions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dismissed_suggestions_user_id'), table_name='dismissed_suggestions')
    op.drop_table('dismissed_suggestions')
    # ### end Alembic commands ###
